version: '3.8'

services:
  spring-app:
    image: kbulkup-spring:latest
    container_name: kbulkup
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prd
    volumes:
      - app_logs:/usr/local/tomcat/logs
    networks:
      - kbulkup-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongodb:
    image: mongo:7.0
    container_name: kbulkup-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - kbulkup-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: kbulkup-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kbulkup-network
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      retries: 10


volumes:
  app_logs:
  mongodb_data:
  redis_data:

networks:
  kbulkup-network:
    driver: bridge

